TIMEOUT_MELB_MAIN = 'https://www.timeout.com/melbourne'
TIMEOUT_MELB_RESTAURANTS = 'https://www.timeout.com/melbourne/restaurants/'
TIMEOUT_MELB_LATEST_REVIEWS = 'https://www.timeout.com/melbourne/restaurants/melbourne-restaurant-and-cafe-reviews'
TIMEOUT_MELB_INDUSTRY_BEANS = 'https://www.timeout.com/melbourne/restaurants/industry-beans-fitzroy'
TIMEOUT_MELB_BEST_RESTAURANTS_LIST = 'https://www.timeout.com/melbourne/restaurants/the-best-restaurants-in-melbourne'
